baseURL = 'https://amoritasolutions.com/'
languageCode = 'en-us'
title = 'Amorita Solutions LLC'

# We leave theme blank because we built our custom layout in layouts/
theme = 'amorita-khaki' 

# Disable injecting default generator meta tags for a cleaner head
disableHugoGeneratorInject = true

[params]
  description = "Global C2C, US Federal Contracting, and Cloud-Native Software Engineering"
  github_handle = "mattcarp12"

[markup.goldmark.renderer]
  # Allows us to use raw HTML in our markdown files if we ever need it
  unsafe = true